#include "hal_usb.h"
#include "hal_gpio.h"
#include "pin_config.h"
#include "config.h"
#include <string.h>

/* USB Device Custom HID middleware, generated by hand to mirror CubeMX's
 * output (no CubeMX GUI in this environment — see CLAUDE.md's CubeMX
 * regen workflow). Symbols come from:
 *   USB_Device/App/usb_device.c              -> hUsbDeviceFS
 *   USB_Device/App/usbd_custom_hid_if.c      -> CUSTOM_HID_OutEvent_FS
 *                                                forwards into hal_usb_on_rx()
 *   Middlewares/.../usbd_customhid.c         -> USBD_CUSTOM_HID_SendReport()
 * hUsbDeviceFS is defined in usb_device.c but not exported via its header
 * (ST's own template omits it) — hence the explicit extern here. */
#include "usbd_def.h"
#include "usbd_core.h"
#include "usbd_customhid.h"
#include "stm32g0xx_hal.h"

extern USBD_HandleTypeDef hUsbDeviceFS;

static HalUsbRxCallback   s_rx_cb        = 0;
static uint8_t            s_tx_buf[USB_HID_REPORT_SIZE];
static bool               s_attached     = false;
static volatile uint32_t  s_usb_irq_count     = 0;
static volatile uint32_t  s_usb_reset_count   = 0;
static volatile uint32_t  s_usb_setup_count   = 0;
static volatile uint32_t  s_usb_suspend_count = 0;
static volatile uint32_t  s_usb_err_count     = 0;
static volatile uint32_t  s_usb_pmaovr_count  = 0;
static volatile uint32_t  s_usb_ctr_count     = 0;
static volatile uint32_t  s_usb_wkup_count    = 0;
static volatile uint32_t  s_usb_attach_toggles = 0;

void hal_usb_isr_tick(void)
{
    /* Sampled BEFORE HAL_PCD_IRQHandler processes/clears ISTR, so this
     * sees every flag that was pending on entry — which event(s) are
     * actually driving the interrupt storm. */
    uint32_t istr = USB_DRD_FS->ISTR;
    if (istr & USB_ISTR_ERR)    { s_usb_err_count++; }
    if (istr & USB_ISTR_PMAOVR) { s_usb_pmaovr_count++; }
    if (istr & USB_ISTR_CTR)    { s_usb_ctr_count++; }
    if (istr & USB_ISTR_WKUP)   { s_usb_wkup_count++; }
    s_usb_irq_count++;
}
void hal_usb_note_reset(void)   { s_usb_reset_count++; }
void hal_usb_note_setup(void)   { s_usb_setup_count++; }
void hal_usb_note_suspend(void) { s_usb_suspend_count++; }

void hal_usb_get_debug(HalUsbDebug *out)
{
    if (!out) {
        return;
    }
    out->attached      = s_attached ? 1U : 0U;
    out->vbus_pin       = hal_gpio_get(VBUS_SENSE_PORT, VBUS_SENSE_PIN) ? 1U : 0U;
    out->dev_state      = (uint8_t)hUsbDeviceFS.dev_state;
    out->dppu           = (USB_DRD_FS->BCDR & USB_BCDR_DPPU) ? 1U : 0U;
    out->fnr            = (uint16_t)(USB_DRD_FS->FNR & USB_FNR_FN);
    out->crs_isr        = CRS->ISR;
    out->irq_count       = s_usb_irq_count;
    out->reset_count     = s_usb_reset_count;
    out->setup_count     = s_usb_setup_count;
    out->suspend_count   = s_usb_suspend_count;
    out->err_count       = s_usb_err_count;
    out->pmaovr_count    = s_usb_pmaovr_count;
    out->ctr_count       = s_usb_ctr_count;
    out->wkup_count      = s_usb_wkup_count;
    out->attach_toggles  = s_usb_attach_toggles;
}

void hal_usb_init(void)
{
    /* hUsbDeviceFS / USB middleware are initialised by MX_USB_Device_Init
     * in usb_device.c (called from main()), which also calls USBD_Start().
     *
     * Detach again here: on this board USB DM/DP sit on the PA9/PA10 pads
     * (SYSCFG PA11/PA12 remap, LQFP64). With the stack started but no host
     * connected, those lines float and the USB peripheral raises bus
     * reset/error interrupts continuously at NVIC priority 0, starving the
     * cooperative scheduler (the LED heartbeat freezes). The device is
     * attached only while VBUS is present — see hal_usb_update(), pumped
     * from task_usb every scheduler tick.
     *
     * s_rx_cb is NOT reset here: svc_usb_init() registers its callback
     * before calling this and must not have it clobbered. */
    USBD_Stop(&hUsbDeviceFS);
    s_attached = false;
}

void hal_usb_register_rx_callback(HalUsbRxCallback cb)
{
    s_rx_cb = cb;
}

void hal_usb_on_rx(const uint8_t *data, uint16_t len)
{
    if (s_rx_cb && data) {
        s_rx_cb(data, len);
    }
}

bool hal_usb_is_connected(void)
{
    /* True if VBUS is high AND USB stack reports configured. VBUS_SENSE
     * is the "physically plugged in" signal; USBD_STATE_CONFIGURED is the
     * stack-level "host finished enumeration" signal — both matter, since
     * a plugged-in-but-not-yet-enumerated device can't send/receive. */
    if (!hal_gpio_get(VBUS_SENSE_PORT, VBUS_SENSE_PIN)) {
        return false;
    }
    return hUsbDeviceFS.dev_state == USBD_STATE_CONFIGURED;
}

bool hal_usb_send(const uint8_t *data, uint16_t len)
{
    if (!hal_usb_is_connected() || data == 0 || len == 0) {
        return false;
    }
    /* Pad to full HID report size — the descriptor advertises a fixed
     * 64-byte IN report and host stacks expect that exact length. The
     * only real caller (svc_api.c's send_packet()) already builds a
     * full, zero-padded USB_HID_REPORT_SIZE frame, so copy == sizeof
     * s_tx_buf in practice and this memset is a no-op — kept defensive
     * for a hypothetical future caller passing len < USB_HID_REPORT_SIZE,
     * but only zeroing the actual remainder instead of always re-zeroing
     * all 64 bytes first. */
    uint16_t copy = len > USB_HID_REPORT_SIZE ? USB_HID_REPORT_SIZE : len;
    memcpy(s_tx_buf, data, copy);
    if (copy < sizeof(s_tx_buf)) {
        memset(s_tx_buf + copy, 0, sizeof(s_tx_buf) - copy);
    }

    /* USBD_CUSTOM_HID_SendReport may return USBD_BUSY when a previous IN
     * report is still in flight (common at high stream rates). Caller
     * treats false as "try again next tick". */
    uint8_t rc = USBD_CUSTOM_HID_SendReport(&hUsbDeviceFS, s_tx_buf, USB_HID_REPORT_SIZE);
    return rc == (uint8_t)USBD_OK;
}

void hal_usb_update(void)
{
    /* Attach the USB device only while VBUS is present; detach as soon as
     * the cable is pulled. Leaving the peripheral connected with the data
     * lines floating produces a priority-0 interrupt storm (see
     * hal_usb_init()). VBUS_SENSE is PA2, driven high by USB-present on
     * REV B (same signal svc_battery uses); read it raw here — a couple of
     * spurious start/stop cycles on a bouncy edge are harmless. */
    bool vbus = hal_gpio_get(VBUS_SENSE_PORT, VBUS_SENSE_PIN);

    if (vbus && !s_attached) {
        if (USBD_Start(&hUsbDeviceFS) == USBD_OK) {
            s_attached = true;
        }
        s_usb_attach_toggles++;
    } else if (!vbus && s_attached) {
        USBD_Stop(&hUsbDeviceFS);
        s_attached = false;
        s_usb_attach_toggles++;
    }
}
