#include "hal_usb.h"
#include "hal_gpio.h"
#include "pin_config.h"
#include "config.h"
#include <string.h>

/* USB Device Custom HID middleware, generated by hand to mirror CubeMX's
 * output (no CubeMX GUI in this environment — see CLAUDE.md's CubeMX
 * regen workflow). Symbols come from:
 *   USB_Device/App/usb_device.c              -> hUsbDeviceFS
 *   USB_Device/App/usbd_custom_hid_if.c      -> CUSTOM_HID_OutEvent_FS
 *                                                forwards into hal_usb_on_rx()
 *   Middlewares/.../usbd_customhid.c         -> USBD_CUSTOM_HID_SendReport()
 * hUsbDeviceFS is defined in usb_device.c but not exported via its header
 * (ST's own template omits it) — hence the explicit extern here. */
#include "usbd_def.h"
#include "usbd_customhid.h"

extern USBD_HandleTypeDef hUsbDeviceFS;

static HalUsbRxCallback s_rx_cb       = 0;
static uint8_t          s_tx_buf[USB_HID_REPORT_SIZE];

void hal_usb_init(void)
{
    /* hUsbDeviceFS / USB middleware are initialised by MX_USB_Device_Init
     * in usb_device.c (called from main()). Nothing to do here — s_rx_cb
     * is NOT reset in this function: svc_usb_init() registers its callback
     * via hal_usb_register_rx_callback() before calling this, and this
     * function running after that registration must not clobber it. */
}

void hal_usb_register_rx_callback(HalUsbRxCallback cb)
{
    s_rx_cb = cb;
}

void hal_usb_on_rx(const uint8_t *data, uint16_t len)
{
    if (s_rx_cb && data) {
        s_rx_cb(data, len);
    }
}

bool hal_usb_is_connected(void)
{
    /* True if VBUS is high AND USB stack reports configured. VBUS_SENSE
     * is the "physically plugged in" signal; USBD_STATE_CONFIGURED is the
     * stack-level "host finished enumeration" signal — both matter, since
     * a plugged-in-but-not-yet-enumerated device can't send/receive. */
    if (!hal_gpio_get(VBUS_SENSE_PORT, VBUS_SENSE_PIN)) {
        return false;
    }
    return hUsbDeviceFS.dev_state == USBD_STATE_CONFIGURED;
}

bool hal_usb_send(const uint8_t *data, uint16_t len)
{
    if (!hal_usb_is_connected() || data == 0 || len == 0) {
        return false;
    }
    /* Pad to full HID report size — the descriptor advertises a fixed
     * 64-byte IN report and host stacks expect that exact length. The
     * only real caller (svc_api.c's send_packet()) already builds a
     * full, zero-padded USB_HID_REPORT_SIZE frame, so copy == sizeof
     * s_tx_buf in practice and this memset is a no-op — kept defensive
     * for a hypothetical future caller passing len < USB_HID_REPORT_SIZE,
     * but only zeroing the actual remainder instead of always re-zeroing
     * all 64 bytes first. */
    uint16_t copy = len > USB_HID_REPORT_SIZE ? USB_HID_REPORT_SIZE : len;
    memcpy(s_tx_buf, data, copy);
    if (copy < sizeof(s_tx_buf)) {
        memset(s_tx_buf + copy, 0, sizeof(s_tx_buf) - copy);
    }

    /* USBD_CUSTOM_HID_SendReport may return USBD_BUSY when a previous IN
     * report is still in flight (common at high stream rates). Caller
     * treats false as "try again next tick". */
    uint8_t rc = USBD_CUSTOM_HID_SendReport(&hUsbDeviceFS, s_tx_buf, USB_HID_REPORT_SIZE);
    return rc == (uint8_t)USBD_OK;
}

void hal_usb_update(void)
{
    /* Nothing to poll here today — hal_usb_is_connected() reads live
     * state on every call. Kept as a scheduler-callable hook (mirrors
     * every other hal_*_update()) for whatever future USB-level polling
     * turns out to be needed (e.g. remote wakeup, suspend handling). */
}
