/* GENERATED by tools/gen_api.py from tools/api_spec.py -- do not edit; edit the spec and regenerate. */
#ifndef SVC_API_DEFS_H
#define SVC_API_DEFS_H

#include <stdint.h>
#include <stdbool.h>
#include "svc_api_core.h"

#define API2_VERSION      3U
#define API2_MAX_PAYLOAD  122U

/* categories */
#define API2_CAT_SYSTEM         0x0U
#define API2_CAT_COMMANDS       0x1U
#define API2_CAT_CALIBRATIONS   0x2U
#define API2_CAT_SETTINGS       0x3U
#define API2_CAT_MEASUREMENTS   0x4U
#define API2_CAT_TOPICS         0x5U
#define API2_CAT_DEBUG          0x6U
#define API2_CAT_DIAGNOSTICS    0x7U
#define API2_CAT_BULK           0x8U
#define API2_CAT_PROCEDURES     0x9U

/* resource ids */
#define API2_RES_SYSTEM_IDENTITY                     0x00U
#define API2_RES_SYSTEM_STATE                        0x01U
#define API2_RES_SYSTEM_HEALTH                       0x02U
#define API2_RES_SYSTEM_RTC                          0x03U
#define API2_RES_COMMANDS_POWER_OFF                  0x40U
#define API2_RES_COMMANDS_REBOOT                     0x41U
#define API2_RES_COMMANDS_REBOOT_DFU                 0x42U
#define API2_RES_COMMANDS_FORCE_CHARGE               0x43U
#define API2_RES_COMMANDS_END_CHARGING               0x44U
#define API2_RES_COMMANDS_CHARGE_INHIBIT             0x45U
#define API2_RES_COMMANDS_TILT_DEMOD                 0x50U
#define API2_RES_COMMANDS_ZERO_CAL                   0x51U
#define API2_RES_COMMANDS_PRECISION                  0x52U
#define API2_RES_COMMANDS_FACTORY_DEFAULTS           0x60U
#define API2_RES_COMMANDS_SERVICE_END                0x62U
#define API2_RES_COMMANDS_CLEAR_COUNTERS             0x61U
#define API2_RES_COMMANDS_TEST_BEEP                  0x70U
#define API2_RES_COMMANDS_POWER_TEST                 0x71U
#define API2_RES_COMMANDS_PIN_TEST                   0x72U
#define API2_RES_COMMANDS_FAULT_TEST                 0x76U
#define API2_RES_COMMANDS_RAIL                       0x73U
#define API2_RES_CALIBRATIONS_S1_K                   0x40U
#define API2_RES_CALIBRATIONS_S1_ZERO                0x41U
#define API2_RES_CALIBRATIONS_S1_PHASE               0x42U
#define API2_RES_CALIBRATIONS_S1_INVERT              0x43U
#define API2_RES_CALIBRATIONS_S2_K                   0x44U
#define API2_RES_CALIBRATIONS_S2_ZERO                0x45U
#define API2_RES_CALIBRATIONS_S2_PHASE               0x46U
#define API2_RES_CALIBRATIONS_S2_INVERT              0x47U
#define API2_RES_CALIBRATIONS_VBAT_SCALE_NUM         0x50U
#define API2_RES_CALIBRATIONS_VBAT_SCALE_DEN         0x51U
#define API2_RES_CALIBRATIONS_VBAT_OFFSET            0x52U
#define API2_RES_CALIBRATIONS_TMP236_SEG1_VOFFS      0x60U
#define API2_RES_CALIBRATIONS_TMP236_SEG1_NUM        0x61U
#define API2_RES_CALIBRATIONS_TMP236_SEG1_DEN        0x62U
#define API2_RES_CALIBRATIONS_TMP236_SEG_BOUNDARY    0x63U
#define API2_RES_CALIBRATIONS_TMP236_SEG2_VOFFS      0x64U
#define API2_RES_CALIBRATIONS_TMP236_SEG2_NUM        0x65U
#define API2_RES_CALIBRATIONS_TMP236_SEG2_DEN        0x66U
#define API2_RES_CALIBRATIONS_TMP236_SEG2_TINFL      0x67U
#define API2_RES_CALIBRATIONS_LM35_SCALE             0x68U
#define API2_RES_CALIBRATIONS_RTC_TRIM               0x70U
#define API2_RES_SETTINGS_TASK_SENSORS               0x40U
#define API2_RES_SETTINGS_TASK_BLE                   0x41U
#define API2_RES_SETTINGS_TASK_USB                   0x42U
#define API2_RES_SETTINGS_TASK_BATTERY               0x43U
#define API2_RES_SETTINGS_TASK_TEMPERATURE           0x44U
#define API2_RES_SETTINGS_BATTERY_CRITICAL           0x50U
#define API2_RES_SETTINGS_BATTERY_LOW                0x51U
#define API2_RES_SETTINGS_BATTERY_CHARGE_START       0x52U
#define API2_RES_SETTINGS_AUTO_POWEROFF              0x60U
#define API2_RES_SETTINGS_ENCODER_COUNTS_PER_DETENT  0x61U
#define API2_RES_MEASUREMENTS_ONBOARD_TEMP           0x00U
#define API2_RES_MEASUREMENTS_BATTERY_MV             0x01U
#define API2_RES_MEASUREMENTS_BATTERY_SOC            0x02U
#define API2_RES_MEASUREMENTS_BME_TEMP               0x03U
#define API2_RES_MEASUREMENTS_BME_PRESSURE           0x04U
#define API2_RES_MEASUREMENTS_BME_HUMIDITY           0x05U
#define API2_RES_MEASUREMENTS_BME_OK                 0x06U
#define API2_RES_MEASUREMENTS_EXT_TEMP               0x07U
#define API2_RES_MEASUREMENTS_EXT_TEMP_OK            0x08U
#define API2_RES_MEASUREMENTS_TILT_S1                0x09U
#define API2_RES_MEASUREMENTS_TILT_S2                0x0AU
#define API2_RES_MEASUREMENTS_TILT_DIFF              0x0BU
#define API2_RES_MEASUREMENTS_TILT_FLAGS             0x0CU
#define API2_RES_MEASUREMENTS_TILT_SEQ               0x0DU
#define API2_RES_TOPICS_ENV                          0x00U
#define API2_RES_TOPICS_STATUS                       0x01U
#define API2_RES_TOPICS_LIVE                         0x02U
#define API2_RES_TOPICS_RAW                          0x03U
#define API2_RES_TOPICS_PHASOR_STREAM                0x04U
#define API2_RES_TOPICS_SIGNAL_DIAG                  0x05U
#define API2_RES_DEBUG_LOG                           0x00U
#define API2_RES_DIAGNOSTICS_ADC                     0x00U
#define API2_RES_DIAGNOSTICS_POWER                   0x01U
#define API2_RES_DIAGNOSTICS_TILT_DEMOD              0x02U
#define API2_RES_BULK_RAW_ADC                        0x00U
#define API2_RES_PROCEDURES_ZERO_CAL                 0x00U
#define API2_RES_PROCEDURES_PRECISION                0x01U

/* opcodes: API2_OP_<CATEGORY>_<RESOURCE>_<VERB> */
#define API2_OP_SYSTEM_IDENTITY_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SYSTEM, API2_RES_SYSTEM_IDENTITY)
#define API2_OP_SYSTEM_STATE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SYSTEM, API2_RES_SYSTEM_STATE)
#define API2_OP_SYSTEM_HEALTH_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SYSTEM, API2_RES_SYSTEM_HEALTH)
#define API2_OP_SYSTEM_RTC_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SYSTEM, API2_RES_SYSTEM_RTC)
#define API2_OP_SYSTEM_RTC_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SYSTEM, API2_RES_SYSTEM_RTC)
#define API2_OP_COMMANDS_POWER_OFF_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_POWER_OFF)
#define API2_OP_COMMANDS_REBOOT_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_REBOOT)
#define API2_OP_COMMANDS_REBOOT_DFU_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_REBOOT_DFU)
#define API2_OP_COMMANDS_FORCE_CHARGE_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_FORCE_CHARGE)
#define API2_OP_COMMANDS_END_CHARGING_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_END_CHARGING)
#define API2_OP_COMMANDS_CHARGE_INHIBIT_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_CHARGE_INHIBIT)
#define API2_OP_COMMANDS_TILT_DEMOD_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_TILT_DEMOD)
#define API2_OP_COMMANDS_ZERO_CAL_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_ZERO_CAL)
#define API2_OP_COMMANDS_PRECISION_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_PRECISION)
#define API2_OP_COMMANDS_FACTORY_DEFAULTS_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_FACTORY_DEFAULTS)
#define API2_OP_COMMANDS_SERVICE_END_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_SERVICE_END)
#define API2_OP_COMMANDS_CLEAR_COUNTERS_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_CLEAR_COUNTERS)
#define API2_OP_COMMANDS_TEST_BEEP_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_TEST_BEEP)
#define API2_OP_COMMANDS_POWER_TEST_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_POWER_TEST)
#define API2_OP_COMMANDS_PIN_TEST_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_PIN_TEST)
#define API2_OP_COMMANDS_FAULT_TEST_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_FAULT_TEST)
#define API2_OP_COMMANDS_RAIL_EXECUTE      API2_OPCODE(API2_VERB_EXECUTE, API2_CAT_COMMANDS, API2_RES_COMMANDS_RAIL)
#define API2_OP_CALIBRATIONS_S1_K_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_K)
#define API2_OP_CALIBRATIONS_S1_K_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_K)
#define API2_OP_CALIBRATIONS_S1_ZERO_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_ZERO)
#define API2_OP_CALIBRATIONS_S1_ZERO_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_ZERO)
#define API2_OP_CALIBRATIONS_S1_PHASE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_PHASE)
#define API2_OP_CALIBRATIONS_S1_PHASE_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_PHASE)
#define API2_OP_CALIBRATIONS_S1_INVERT_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_INVERT)
#define API2_OP_CALIBRATIONS_S1_INVERT_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S1_INVERT)
#define API2_OP_CALIBRATIONS_S2_K_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_K)
#define API2_OP_CALIBRATIONS_S2_K_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_K)
#define API2_OP_CALIBRATIONS_S2_ZERO_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_ZERO)
#define API2_OP_CALIBRATIONS_S2_ZERO_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_ZERO)
#define API2_OP_CALIBRATIONS_S2_PHASE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_PHASE)
#define API2_OP_CALIBRATIONS_S2_PHASE_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_PHASE)
#define API2_OP_CALIBRATIONS_S2_INVERT_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_INVERT)
#define API2_OP_CALIBRATIONS_S2_INVERT_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_S2_INVERT)
#define API2_OP_CALIBRATIONS_VBAT_SCALE_NUM_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_VBAT_SCALE_NUM)
#define API2_OP_CALIBRATIONS_VBAT_SCALE_NUM_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_VBAT_SCALE_NUM)
#define API2_OP_CALIBRATIONS_VBAT_SCALE_DEN_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_VBAT_SCALE_DEN)
#define API2_OP_CALIBRATIONS_VBAT_SCALE_DEN_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_VBAT_SCALE_DEN)
#define API2_OP_CALIBRATIONS_VBAT_OFFSET_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_VBAT_OFFSET)
#define API2_OP_CALIBRATIONS_VBAT_OFFSET_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_VBAT_OFFSET)
#define API2_OP_CALIBRATIONS_TMP236_SEG1_VOFFS_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG1_VOFFS)
#define API2_OP_CALIBRATIONS_TMP236_SEG1_VOFFS_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG1_VOFFS)
#define API2_OP_CALIBRATIONS_TMP236_SEG1_NUM_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG1_NUM)
#define API2_OP_CALIBRATIONS_TMP236_SEG1_NUM_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG1_NUM)
#define API2_OP_CALIBRATIONS_TMP236_SEG1_DEN_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG1_DEN)
#define API2_OP_CALIBRATIONS_TMP236_SEG1_DEN_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG1_DEN)
#define API2_OP_CALIBRATIONS_TMP236_SEG_BOUNDARY_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG_BOUNDARY)
#define API2_OP_CALIBRATIONS_TMP236_SEG_BOUNDARY_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG_BOUNDARY)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_VOFFS_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_VOFFS)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_VOFFS_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_VOFFS)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_NUM_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_NUM)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_NUM_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_NUM)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_DEN_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_DEN)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_DEN_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_DEN)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_TINFL_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_TINFL)
#define API2_OP_CALIBRATIONS_TMP236_SEG2_TINFL_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_TMP236_SEG2_TINFL)
#define API2_OP_CALIBRATIONS_LM35_SCALE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_LM35_SCALE)
#define API2_OP_CALIBRATIONS_LM35_SCALE_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_LM35_SCALE)
#define API2_OP_CALIBRATIONS_RTC_TRIM_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_RTC_TRIM)
#define API2_OP_CALIBRATIONS_RTC_TRIM_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_CALIBRATIONS, API2_RES_CALIBRATIONS_RTC_TRIM)
#define API2_OP_SETTINGS_TASK_SENSORS_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_SENSORS)
#define API2_OP_SETTINGS_TASK_SENSORS_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_SENSORS)
#define API2_OP_SETTINGS_TASK_BLE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_BLE)
#define API2_OP_SETTINGS_TASK_BLE_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_BLE)
#define API2_OP_SETTINGS_TASK_USB_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_USB)
#define API2_OP_SETTINGS_TASK_USB_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_USB)
#define API2_OP_SETTINGS_TASK_BATTERY_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_BATTERY)
#define API2_OP_SETTINGS_TASK_BATTERY_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_BATTERY)
#define API2_OP_SETTINGS_TASK_TEMPERATURE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_TEMPERATURE)
#define API2_OP_SETTINGS_TASK_TEMPERATURE_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_TASK_TEMPERATURE)
#define API2_OP_SETTINGS_BATTERY_CRITICAL_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_BATTERY_CRITICAL)
#define API2_OP_SETTINGS_BATTERY_CRITICAL_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_BATTERY_CRITICAL)
#define API2_OP_SETTINGS_BATTERY_LOW_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_BATTERY_LOW)
#define API2_OP_SETTINGS_BATTERY_LOW_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_BATTERY_LOW)
#define API2_OP_SETTINGS_BATTERY_CHARGE_START_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_BATTERY_CHARGE_START)
#define API2_OP_SETTINGS_BATTERY_CHARGE_START_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_BATTERY_CHARGE_START)
#define API2_OP_SETTINGS_AUTO_POWEROFF_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_AUTO_POWEROFF)
#define API2_OP_SETTINGS_AUTO_POWEROFF_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_AUTO_POWEROFF)
#define API2_OP_SETTINGS_ENCODER_COUNTS_PER_DETENT_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_SETTINGS, API2_RES_SETTINGS_ENCODER_COUNTS_PER_DETENT)
#define API2_OP_SETTINGS_ENCODER_COUNTS_PER_DETENT_SET          API2_OPCODE(API2_VERB_SET, API2_CAT_SETTINGS, API2_RES_SETTINGS_ENCODER_COUNTS_PER_DETENT)
#define API2_OP_MEASUREMENTS_ONBOARD_TEMP_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_ONBOARD_TEMP)
#define API2_OP_MEASUREMENTS_ONBOARD_TEMP_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_ONBOARD_TEMP)
#define API2_OP_MEASUREMENTS_ONBOARD_TEMP_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_ONBOARD_TEMP)
#define API2_OP_MEASUREMENTS_BATTERY_MV_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BATTERY_MV)
#define API2_OP_MEASUREMENTS_BATTERY_MV_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BATTERY_MV)
#define API2_OP_MEASUREMENTS_BATTERY_MV_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BATTERY_MV)
#define API2_OP_MEASUREMENTS_BATTERY_SOC_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BATTERY_SOC)
#define API2_OP_MEASUREMENTS_BATTERY_SOC_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BATTERY_SOC)
#define API2_OP_MEASUREMENTS_BATTERY_SOC_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BATTERY_SOC)
#define API2_OP_MEASUREMENTS_BME_TEMP_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_TEMP)
#define API2_OP_MEASUREMENTS_BME_TEMP_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_TEMP)
#define API2_OP_MEASUREMENTS_BME_TEMP_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_TEMP)
#define API2_OP_MEASUREMENTS_BME_PRESSURE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_PRESSURE)
#define API2_OP_MEASUREMENTS_BME_PRESSURE_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_PRESSURE)
#define API2_OP_MEASUREMENTS_BME_PRESSURE_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_PRESSURE)
#define API2_OP_MEASUREMENTS_BME_HUMIDITY_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_HUMIDITY)
#define API2_OP_MEASUREMENTS_BME_HUMIDITY_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_HUMIDITY)
#define API2_OP_MEASUREMENTS_BME_HUMIDITY_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_HUMIDITY)
#define API2_OP_MEASUREMENTS_BME_OK_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_OK)
#define API2_OP_MEASUREMENTS_BME_OK_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_OK)
#define API2_OP_MEASUREMENTS_BME_OK_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_BME_OK)
#define API2_OP_MEASUREMENTS_EXT_TEMP_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_EXT_TEMP)
#define API2_OP_MEASUREMENTS_EXT_TEMP_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_EXT_TEMP)
#define API2_OP_MEASUREMENTS_EXT_TEMP_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_EXT_TEMP)
#define API2_OP_MEASUREMENTS_EXT_TEMP_OK_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_EXT_TEMP_OK)
#define API2_OP_MEASUREMENTS_EXT_TEMP_OK_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_EXT_TEMP_OK)
#define API2_OP_MEASUREMENTS_EXT_TEMP_OK_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_EXT_TEMP_OK)
#define API2_OP_MEASUREMENTS_TILT_S1_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_S1)
#define API2_OP_MEASUREMENTS_TILT_S1_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_S1)
#define API2_OP_MEASUREMENTS_TILT_S1_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_S1)
#define API2_OP_MEASUREMENTS_TILT_S2_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_S2)
#define API2_OP_MEASUREMENTS_TILT_S2_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_S2)
#define API2_OP_MEASUREMENTS_TILT_S2_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_S2)
#define API2_OP_MEASUREMENTS_TILT_DIFF_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_DIFF)
#define API2_OP_MEASUREMENTS_TILT_DIFF_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_DIFF)
#define API2_OP_MEASUREMENTS_TILT_DIFF_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_DIFF)
#define API2_OP_MEASUREMENTS_TILT_FLAGS_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_FLAGS)
#define API2_OP_MEASUREMENTS_TILT_FLAGS_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_FLAGS)
#define API2_OP_MEASUREMENTS_TILT_FLAGS_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_FLAGS)
#define API2_OP_MEASUREMENTS_TILT_SEQ_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_SEQ)
#define API2_OP_MEASUREMENTS_TILT_SEQ_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_SEQ)
#define API2_OP_MEASUREMENTS_TILT_SEQ_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_MEASUREMENTS, API2_RES_MEASUREMENTS_TILT_SEQ)
#define API2_OP_TOPICS_ENV_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_TOPICS, API2_RES_TOPICS_ENV)
#define API2_OP_TOPICS_ENV_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_ENV)
#define API2_OP_TOPICS_ENV_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_ENV)
#define API2_OP_TOPICS_STATUS_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_TOPICS, API2_RES_TOPICS_STATUS)
#define API2_OP_TOPICS_STATUS_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_STATUS)
#define API2_OP_TOPICS_STATUS_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_STATUS)
#define API2_OP_TOPICS_LIVE_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_TOPICS, API2_RES_TOPICS_LIVE)
#define API2_OP_TOPICS_LIVE_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_LIVE)
#define API2_OP_TOPICS_LIVE_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_LIVE)
#define API2_OP_TOPICS_RAW_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_TOPICS, API2_RES_TOPICS_RAW)
#define API2_OP_TOPICS_RAW_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_RAW)
#define API2_OP_TOPICS_RAW_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_RAW)
#define API2_OP_TOPICS_PHASOR_STREAM_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_PHASOR_STREAM)
#define API2_OP_TOPICS_PHASOR_STREAM_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_PHASOR_STREAM)
#define API2_OP_TOPICS_SIGNAL_DIAG_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_TOPICS, API2_RES_TOPICS_SIGNAL_DIAG)
#define API2_OP_TOPICS_SIGNAL_DIAG_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_SIGNAL_DIAG)
#define API2_OP_TOPICS_SIGNAL_DIAG_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_TOPICS, API2_RES_TOPICS_SIGNAL_DIAG)
#define API2_OP_DEBUG_LOG_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_DEBUG, API2_RES_DEBUG_LOG)
#define API2_OP_DEBUG_LOG_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_DEBUG, API2_RES_DEBUG_LOG)
#define API2_OP_DIAGNOSTICS_ADC_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_DIAGNOSTICS, API2_RES_DIAGNOSTICS_ADC)
#define API2_OP_DIAGNOSTICS_POWER_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_DIAGNOSTICS, API2_RES_DIAGNOSTICS_POWER)
#define API2_OP_DIAGNOSTICS_TILT_DEMOD_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_DIAGNOSTICS, API2_RES_DIAGNOSTICS_TILT_DEMOD)
#define API2_OP_BULK_RAW_ADC_START_BULK   API2_OPCODE(API2_VERB_START_BULK, API2_CAT_BULK, API2_RES_BULK_RAW_ADC)
#define API2_OP_BULK_RAW_ADC_CANCEL_BULK  API2_OPCODE(API2_VERB_CANCEL_BULK, API2_CAT_BULK, API2_RES_BULK_RAW_ADC)
#define API2_OP_PROCEDURES_ZERO_CAL_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_PROCEDURES, API2_RES_PROCEDURES_ZERO_CAL)
#define API2_OP_PROCEDURES_ZERO_CAL_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_PROCEDURES, API2_RES_PROCEDURES_ZERO_CAL)
#define API2_OP_PROCEDURES_ZERO_CAL_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_PROCEDURES, API2_RES_PROCEDURES_ZERO_CAL)
#define API2_OP_PROCEDURES_PRECISION_GET          API2_OPCODE(API2_VERB_GET, API2_CAT_PROCEDURES, API2_RES_PROCEDURES_PRECISION)
#define API2_OP_PROCEDURES_PRECISION_SUBSCRIBE    API2_OPCODE(API2_VERB_SUBSCRIBE, API2_CAT_PROCEDURES, API2_RES_PROCEDURES_PRECISION)
#define API2_OP_PROCEDURES_PRECISION_UNSUBSCRIBE  API2_OPCODE(API2_VERB_UNSUBSCRIBE, API2_CAT_PROCEDURES, API2_RES_PROCEDURES_PRECISION)

/* wire payloads (after the status byte / after [issue_seq][page] for pushes); packed, little-endian */
typedef struct {
    uint8_t  fw_major;
    uint8_t  fw_minor;
    uint8_t  fw_patch;
    uint8_t  api_version;
    uint16_t max_payload;
    char     product[16];
    char     serial[8];
    char     build[20];
} __attribute__((packed)) Api2SystemIdentityResponse;
_Static_assert(sizeof(Api2SystemIdentityResponse) == 50U, "Api2SystemIdentityResponse layout");
typedef struct {
    uint8_t  battery_state;
    uint8_t  battery_soc_pct;
    uint16_t battery_mv;
    uint8_t  usb_connected;
    uint8_t  ble_connected;
    uint8_t  charging;
    uint8_t  force_charging;
    uint8_t  charge_inhibited;
    uint8_t  rail_3v3_on;
    uint8_t  rail_5v_on;
    uint8_t  demod_running;
    uint8_t  phasor_stream_active;
    uint8_t  bulk_active;
    uint8_t  service_mode;
} __attribute__((packed)) Api2SystemStateResponse;
_Static_assert(sizeof(Api2SystemStateResponse) == 15U, "Api2SystemStateResponse layout");
typedef struct {
    uint8_t  adc_ok;
    uint8_t  dac_ok;
    uint8_t  ads_ok;
    uint8_t  display_ok;
    uint8_t  bme280_ok;
    uint8_t  eeprom_selftest;
    uint8_t  settings_save_failed;
    uint8_t  woke_from_standby;
    uint8_t  reset_cause;
    uint8_t  rtc_set;
    uint32_t uptime_s;
    uint16_t usb_tx_dropped;
    uint16_t ble_tx_dropped;
    uint16_t uart_tx_dropped;
    uint16_t rx_malformed;
    uint8_t  last_fault_kind;
    uint32_t last_fault_pc;
    uint32_t last_fault_lr;
} __attribute__((packed)) Api2SystemHealthResponse;
_Static_assert(sizeof(Api2SystemHealthResponse) == 31U, "Api2SystemHealthResponse layout");
typedef struct {
    uint16_t year;
    uint8_t  month;
    uint8_t  day;
    uint8_t  weekday;
    uint8_t  hour;
    uint8_t  minute;
    uint8_t  second;
    uint8_t  is_set;
    uint8_t  subsecond;
} __attribute__((packed)) Api2SystemRtcResponse;
_Static_assert(sizeof(Api2SystemRtcResponse) == 10U, "Api2SystemRtcResponse layout");
typedef struct {
    uint16_t year;
    uint8_t  month;
    uint8_t  day;
    uint8_t  hour;
    uint8_t  minute;
    uint8_t  second;
} __attribute__((packed)) Api2SystemRtcRequest;
_Static_assert(sizeof(Api2SystemRtcRequest) == 7U, "Api2SystemRtcRequest layout");
typedef struct {
    uint8_t  inhibit;
} __attribute__((packed)) Api2CommandsChargeInhibitRequest;
_Static_assert(sizeof(Api2CommandsChargeInhibitRequest) == 1U, "Api2CommandsChargeInhibitRequest layout");
typedef struct {
    uint8_t  run;
} __attribute__((packed)) Api2CommandsTiltDemodRequest;
_Static_assert(sizeof(Api2CommandsTiltDemodRequest) == 1U, "Api2CommandsTiltDemodRequest layout");
typedef struct {
    uint8_t  action;
    uint8_t  sensor_mask;
} __attribute__((packed)) Api2CommandsZeroCalRequest;
_Static_assert(sizeof(Api2CommandsZeroCalRequest) == 2U, "Api2CommandsZeroCalRequest layout");
typedef struct {
    uint8_t  action;
} __attribute__((packed)) Api2CommandsPrecisionRequest;
_Static_assert(sizeof(Api2CommandsPrecisionRequest) == 1U, "Api2CommandsPrecisionRequest layout");
typedef struct {
    uint8_t  confirm;
} __attribute__((packed)) Api2CommandsFactoryDefaultsRequest;
_Static_assert(sizeof(Api2CommandsFactoryDefaultsRequest) == 1U, "Api2CommandsFactoryDefaultsRequest layout");
typedef struct {
    uint32_t applied_mask;
} __attribute__((packed)) Api2CommandsPowerTestResponse;
_Static_assert(sizeof(Api2CommandsPowerTestResponse) == 4U, "Api2CommandsPowerTestResponse layout");
typedef struct {
    uint32_t mask;
} __attribute__((packed)) Api2CommandsPowerTestRequest;
_Static_assert(sizeof(Api2CommandsPowerTestRequest) == 4U, "Api2CommandsPowerTestRequest layout");
typedef struct {
    uint8_t  pins;
} __attribute__((packed)) Api2CommandsPinTestRequest;
_Static_assert(sizeof(Api2CommandsPinTestRequest) == 1U, "Api2CommandsPinTestRequest layout");
typedef struct {
    uint8_t  kind;
} __attribute__((packed)) Api2CommandsFaultTestRequest;
_Static_assert(sizeof(Api2CommandsFaultTestRequest) == 1U, "Api2CommandsFaultTestRequest layout");
typedef struct {
    uint32_t applied_mask;
} __attribute__((packed)) Api2CommandsRailResponse;
_Static_assert(sizeof(Api2CommandsRailResponse) == 4U, "Api2CommandsRailResponse layout");
typedef struct {
    uint8_t  rail;
    uint8_t  on;
} __attribute__((packed)) Api2CommandsRailRequest;
_Static_assert(sizeof(Api2CommandsRailRequest) == 2U, "Api2CommandsRailRequest layout");
typedef struct {
    int32_t  value;
} __attribute__((packed)) Api2CalibrationsS1KValue;
_Static_assert(sizeof(Api2CalibrationsS1KValue) == 4U, "Api2CalibrationsS1KValue layout");
typedef struct {
    int32_t  value;
} __attribute__((packed)) Api2CalibrationsS1ZeroValue;
_Static_assert(sizeof(Api2CalibrationsS1ZeroValue) == 4U, "Api2CalibrationsS1ZeroValue layout");
typedef struct {
    int16_t  value;
} __attribute__((packed)) Api2CalibrationsS1PhaseValue;
_Static_assert(sizeof(Api2CalibrationsS1PhaseValue) == 2U, "Api2CalibrationsS1PhaseValue layout");
typedef struct {
    uint8_t  value;
} __attribute__((packed)) Api2CalibrationsS1InvertValue;
_Static_assert(sizeof(Api2CalibrationsS1InvertValue) == 1U, "Api2CalibrationsS1InvertValue layout");
typedef struct {
    int32_t  value;
} __attribute__((packed)) Api2CalibrationsS2KValue;
_Static_assert(sizeof(Api2CalibrationsS2KValue) == 4U, "Api2CalibrationsS2KValue layout");
typedef struct {
    int32_t  value;
} __attribute__((packed)) Api2CalibrationsS2ZeroValue;
_Static_assert(sizeof(Api2CalibrationsS2ZeroValue) == 4U, "Api2CalibrationsS2ZeroValue layout");
typedef struct {
    int16_t  value;
} __attribute__((packed)) Api2CalibrationsS2PhaseValue;
_Static_assert(sizeof(Api2CalibrationsS2PhaseValue) == 2U, "Api2CalibrationsS2PhaseValue layout");
typedef struct {
    uint8_t  value;
} __attribute__((packed)) Api2CalibrationsS2InvertValue;
_Static_assert(sizeof(Api2CalibrationsS2InvertValue) == 1U, "Api2CalibrationsS2InvertValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsVbatScaleNumValue;
_Static_assert(sizeof(Api2CalibrationsVbatScaleNumValue) == 2U, "Api2CalibrationsVbatScaleNumValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsVbatScaleDenValue;
_Static_assert(sizeof(Api2CalibrationsVbatScaleDenValue) == 2U, "Api2CalibrationsVbatScaleDenValue layout");
typedef struct {
    int32_t  value;
} __attribute__((packed)) Api2CalibrationsVbatOffsetValue;
_Static_assert(sizeof(Api2CalibrationsVbatOffsetValue) == 4U, "Api2CalibrationsVbatOffsetValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg1VoffsValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg1VoffsValue) == 2U, "Api2CalibrationsTmp236Seg1VoffsValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg1NumValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg1NumValue) == 2U, "Api2CalibrationsTmp236Seg1NumValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg1DenValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg1DenValue) == 2U, "Api2CalibrationsTmp236Seg1DenValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236SegBoundaryValue;
_Static_assert(sizeof(Api2CalibrationsTmp236SegBoundaryValue) == 2U, "Api2CalibrationsTmp236SegBoundaryValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg2VoffsValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg2VoffsValue) == 2U, "Api2CalibrationsTmp236Seg2VoffsValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg2NumValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg2NumValue) == 2U, "Api2CalibrationsTmp236Seg2NumValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg2DenValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg2DenValue) == 2U, "Api2CalibrationsTmp236Seg2DenValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsTmp236Seg2TinflValue;
_Static_assert(sizeof(Api2CalibrationsTmp236Seg2TinflValue) == 2U, "Api2CalibrationsTmp236Seg2TinflValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2CalibrationsLm35ScaleValue;
_Static_assert(sizeof(Api2CalibrationsLm35ScaleValue) == 2U, "Api2CalibrationsLm35ScaleValue layout");
typedef struct {
    int16_t  value;
} __attribute__((packed)) Api2CalibrationsRtcTrimValue;
_Static_assert(sizeof(Api2CalibrationsRtcTrimValue) == 2U, "Api2CalibrationsRtcTrimValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsTaskSensorsValue;
_Static_assert(sizeof(Api2SettingsTaskSensorsValue) == 2U, "Api2SettingsTaskSensorsValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsTaskBleValue;
_Static_assert(sizeof(Api2SettingsTaskBleValue) == 2U, "Api2SettingsTaskBleValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsTaskUsbValue;
_Static_assert(sizeof(Api2SettingsTaskUsbValue) == 2U, "Api2SettingsTaskUsbValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsTaskBatteryValue;
_Static_assert(sizeof(Api2SettingsTaskBatteryValue) == 2U, "Api2SettingsTaskBatteryValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsTaskTemperatureValue;
_Static_assert(sizeof(Api2SettingsTaskTemperatureValue) == 2U, "Api2SettingsTaskTemperatureValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsBatteryCriticalValue;
_Static_assert(sizeof(Api2SettingsBatteryCriticalValue) == 2U, "Api2SettingsBatteryCriticalValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsBatteryLowValue;
_Static_assert(sizeof(Api2SettingsBatteryLowValue) == 2U, "Api2SettingsBatteryLowValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsBatteryChargeStartValue;
_Static_assert(sizeof(Api2SettingsBatteryChargeStartValue) == 2U, "Api2SettingsBatteryChargeStartValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsAutoPoweroffValue;
_Static_assert(sizeof(Api2SettingsAutoPoweroffValue) == 2U, "Api2SettingsAutoPoweroffValue layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2SettingsEncoderCountsPerDetentValue;
_Static_assert(sizeof(Api2SettingsEncoderCountsPerDetentValue) == 2U, "Api2SettingsEncoderCountsPerDetentValue layout");
typedef struct {
    int16_t  value;
} __attribute__((packed)) Api2MeasurementsOnboardTempResponse;
_Static_assert(sizeof(Api2MeasurementsOnboardTempResponse) == 2U, "Api2MeasurementsOnboardTempResponse layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2MeasurementsBatteryMvResponse;
_Static_assert(sizeof(Api2MeasurementsBatteryMvResponse) == 2U, "Api2MeasurementsBatteryMvResponse layout");
typedef struct {
    uint8_t  value;
} __attribute__((packed)) Api2MeasurementsBatterySocResponse;
_Static_assert(sizeof(Api2MeasurementsBatterySocResponse) == 1U, "Api2MeasurementsBatterySocResponse layout");
typedef struct {
    int16_t  value;
} __attribute__((packed)) Api2MeasurementsBmeTempResponse;
_Static_assert(sizeof(Api2MeasurementsBmeTempResponse) == 2U, "Api2MeasurementsBmeTempResponse layout");
typedef struct {
    uint32_t value;
} __attribute__((packed)) Api2MeasurementsBmePressureResponse;
_Static_assert(sizeof(Api2MeasurementsBmePressureResponse) == 4U, "Api2MeasurementsBmePressureResponse layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2MeasurementsBmeHumidityResponse;
_Static_assert(sizeof(Api2MeasurementsBmeHumidityResponse) == 2U, "Api2MeasurementsBmeHumidityResponse layout");
typedef struct {
    uint8_t  value;
} __attribute__((packed)) Api2MeasurementsBmeOkResponse;
_Static_assert(sizeof(Api2MeasurementsBmeOkResponse) == 1U, "Api2MeasurementsBmeOkResponse layout");
typedef struct {
    int16_t  value;
} __attribute__((packed)) Api2MeasurementsExtTempResponse;
_Static_assert(sizeof(Api2MeasurementsExtTempResponse) == 2U, "Api2MeasurementsExtTempResponse layout");
typedef struct {
    uint8_t  value;
} __attribute__((packed)) Api2MeasurementsExtTempOkResponse;
_Static_assert(sizeof(Api2MeasurementsExtTempOkResponse) == 1U, "Api2MeasurementsExtTempOkResponse layout");
typedef struct {
    float    value;
} __attribute__((packed)) Api2MeasurementsTiltS1Response;
_Static_assert(sizeof(Api2MeasurementsTiltS1Response) == 4U, "Api2MeasurementsTiltS1Response layout");
typedef struct {
    float    value;
} __attribute__((packed)) Api2MeasurementsTiltS2Response;
_Static_assert(sizeof(Api2MeasurementsTiltS2Response) == 4U, "Api2MeasurementsTiltS2Response layout");
typedef struct {
    float    value;
} __attribute__((packed)) Api2MeasurementsTiltDiffResponse;
_Static_assert(sizeof(Api2MeasurementsTiltDiffResponse) == 4U, "Api2MeasurementsTiltDiffResponse layout");
typedef struct {
    uint8_t  value;
} __attribute__((packed)) Api2MeasurementsTiltFlagsResponse;
_Static_assert(sizeof(Api2MeasurementsTiltFlagsResponse) == 1U, "Api2MeasurementsTiltFlagsResponse layout");
typedef struct {
    uint16_t value;
} __attribute__((packed)) Api2MeasurementsTiltSeqResponse;
_Static_assert(sizeof(Api2MeasurementsTiltSeqResponse) == 2U, "Api2MeasurementsTiltSeqResponse layout");
typedef struct {
    int16_t  bme280_temp;
    uint32_t bme280_pressure;
    uint16_t bme280_humidity;
    uint8_t  bme280_ok;
    int16_t  onboard_temp;
    int16_t  external_temp;
    uint8_t  external_temp_ok;
} __attribute__((packed)) Api2TopicsEnvResponse;
_Static_assert(sizeof(Api2TopicsEnvResponse) == 14U, "Api2TopicsEnvResponse layout");
typedef struct {
    uint8_t  battery_state;
    uint8_t  battery_soc_pct;
    uint16_t battery_mv;
    uint8_t  usb_connected;
    uint8_t  ble_connected;
    uint8_t  charging;
    uint8_t  force_charging;
    uint8_t  charge_inhibited;
    uint8_t  rail_3v3_on;
    uint8_t  rail_5v_on;
    uint8_t  demod_running;
    uint8_t  phasor_stream_active;
    uint8_t  bulk_active;
    uint8_t  service_mode;
} __attribute__((packed)) Api2TopicsStatusResponse;
_Static_assert(sizeof(Api2TopicsStatusResponse) == 15U, "Api2TopicsStatusResponse layout");
typedef struct {
    uint16_t seq;
    uint8_t  flags;
    float    tilt_s1;
    float    tilt_s2;
    float    tilt_diff;
} __attribute__((packed)) Api2TopicsLiveResponse;
_Static_assert(sizeof(Api2TopicsLiveResponse) == 15U, "Api2TopicsLiveResponse layout");
typedef struct {
    float    tilt_s1;
    float    residual_s1;
    float    tilt_s2;
    float    residual_s2;
    uint8_t  window_ok_s1;
    uint8_t  window_ok_s2;
    float    tilt_diff;
    uint8_t  window_ok_diff;
} __attribute__((packed)) Api2TopicsRawResponse;
_Static_assert(sizeof(Api2TopicsRawResponse) == 23U, "Api2TopicsRawResponse layout");
typedef struct {
    float    iB;
    float    qB;
    float    iA;
    float    qA;
    float    iS1;
    float    qS1;
    float    iS2;
    float    qS2;
    uint16_t seq;
} __attribute__((packed)) Api2TopicsPhasorStreamPush;
_Static_assert(sizeof(Api2TopicsPhasorStreamPush) == 34U, "Api2TopicsPhasorStreamPush layout");
typedef struct {
    float    rms_mv_ch0;
    float    rms_mv_ch1;
    float    rms_mv_ch2;
    float    rms_mv_ch3;
    float    p2p_mv_ch0;
    float    p2p_mv_ch1;
    float    p2p_mv_ch2;
    float    p2p_mv_ch3;
    float    phase_deg_ch0;
    float    phase_deg_ch1;
    float    phase_deg_ch2;
    float    phase_deg_ch3;
    float    theoretical_tilt_s1;
    float    theoretical_tilt_s2;
} __attribute__((packed)) Api2TopicsSignalDiagResponse;
_Static_assert(sizeof(Api2TopicsSignalDiagResponse) == 56U, "Api2TopicsSignalDiagResponse layout");
typedef struct {
    uint8_t  min_severity;
} __attribute__((packed)) Api2DebugLogSubscribe;
_Static_assert(sizeof(Api2DebugLogSubscribe) == 1U, "Api2DebugLogSubscribe layout");
typedef struct {
    uint16_t id;
    uint16_t status;
    uint16_t mode;
    uint16_t clock;
    uint16_t gain1;
    uint16_t cfg;
    uint16_t clock_expected;
    uint8_t  regs_read_ok;
    uint8_t  ads_ok;
    uint16_t last_capture_samples;
    uint16_t last_capture_drops;
    uint32_t last_capture_ms;
    uint32_t frames_produced;
    uint32_t frames_drained;
    uint32_t tim7_fires;
    uint32_t ring_overflow;
    uint32_t drain_clamped;
    uint32_t framing_err;
    uint32_t crc_err;
    uint32_t run_ms;
    int32_t  frame_deficit;
    int32_t  frame_deficit_min;
    int32_t  frame_deficit_max;
    uint16_t drain_clamp_max;
    uint16_t word0_last;
    uint16_t crc_rx_last;
    uint16_t crc_calc_last;
    uint8_t  fault_code;
    uint32_t now_ms;
} __attribute__((packed)) Api2DiagnosticsAdcResponse;
_Static_assert(sizeof(Api2DiagnosticsAdcResponse) == 81U, "Api2DiagnosticsAdcResponse layout");
typedef struct {
    uint32_t mask;
    uint8_t  rails;
} __attribute__((packed)) Api2DiagnosticsPowerResponse;
_Static_assert(sizeof(Api2DiagnosticsPowerResponse) == 5U, "Api2DiagnosticsPowerResponse layout");
typedef struct {
    uint16_t input_drop;
    uint16_t degenerate;
    uint16_t clip;
    uint16_t amplitude_fault;
    uint16_t max_update_gap_ms;
    uint32_t max_gap_at_uptime_ms;
    uint16_t gap_over_threshold;
    uint8_t  running;
} __attribute__((packed)) Api2DiagnosticsTiltDemodResponse;
_Static_assert(sizeof(Api2DiagnosticsTiltDemodResponse) == 17U, "Api2DiagnosticsTiltDemodResponse layout");
typedef struct {
    uint8_t  page;
} __attribute__((packed)) Api2BulkRawAdcPush;
_Static_assert(sizeof(Api2BulkRawAdcPush) == 1U, "Api2BulkRawAdcPush layout");
typedef struct {
    uint8_t  phase;
    uint16_t progress;
    uint16_t target;
    uint8_t  sensor_mask;
} __attribute__((packed)) Api2ProceduresZeroCalResponse;
_Static_assert(sizeof(Api2ProceduresZeroCalResponse) == 6U, "Api2ProceduresZeroCalResponse layout");
typedef struct {
    uint8_t  phase;
    uint16_t target;
    uint16_t count;
    uint32_t elapsed_ms;
    uint8_t  failed;
    float    tilt_s1;
    float    tilt_s2;
    float    tilt_diff;
    uint8_t  disturbed;
} __attribute__((packed)) Api2ProceduresPrecisionResponse;
_Static_assert(sizeof(Api2ProceduresPrecisionResponse) == 23U, "Api2ProceduresPrecisionResponse layout");

/* handlers: implemented in Services/svc_api_res_*.c; field resources use api_field_handler */
Api2Status api_h_system_identity(const ApiResource *r, ApiCall *c);
Api2Status api_h_system_state(const ApiResource *r, ApiCall *c);
Api2Status api_h_system_health(const ApiResource *r, ApiCall *c);
Api2Status api_h_system_rtc(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_power_off(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_reboot(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_reboot_dfu(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_force_charge(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_end_charging(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_charge_inhibit(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_tilt_demod(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_zero_cal(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_precision(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_factory_defaults(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_service_end(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_clear_counters(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_test_beep(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_power_test(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_pin_test(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_fault_test(const ApiResource *r, ApiCall *c);
Api2Status api_h_commands_rail(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_onboard_temp(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_battery_mv(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_battery_soc(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_bme_temp(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_bme_pressure(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_bme_humidity(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_bme_ok(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_ext_temp(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_ext_temp_ok(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_tilt_s1(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_tilt_s2(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_tilt_diff(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_tilt_flags(const ApiResource *r, ApiCall *c);
Api2Status api_h_measurements_tilt_seq(const ApiResource *r, ApiCall *c);
Api2Status api_h_topics_env(const ApiResource *r, ApiCall *c);
Api2Status api_h_topics_status(const ApiResource *r, ApiCall *c);
Api2Status api_h_topics_live(const ApiResource *r, ApiCall *c);
Api2Status api_h_topics_raw(const ApiResource *r, ApiCall *c);
Api2Status api_h_topics_phasor_stream(const ApiResource *r, ApiCall *c);
Api2Status api_h_topics_signal_diag(const ApiResource *r, ApiCall *c);
Api2Status api_h_debug_log(const ApiResource *r, ApiCall *c);
Api2Status api_h_diagnostics_adc(const ApiResource *r, ApiCall *c);
Api2Status api_h_diagnostics_power(const ApiResource *r, ApiCall *c);
Api2Status api_h_diagnostics_tilt_demod(const ApiResource *r, ApiCall *c);
Api2Status api_h_bulk_raw_adc(const ApiResource *r, ApiCall *c);
Api2Status api_h_procedures_zero_cal(const ApiResource *r, ApiCall *c);
Api2Status api_h_procedures_precision(const ApiResource *r, ApiCall *c);

/* event-subscription operations */
extern const ApiEventOps api_ev_live;
extern const ApiEventOps api_ev_log;
extern const ApiEventOps api_ev_phasor_stream;
extern const ApiEventOps api_ev_precision;
extern const ApiEventOps api_ev_zero_cal;

/* hooks of field resources */
bool api_check_battery_order(uint8_t res, int64_t value);
void api_after_rtc_trim(void);

/* subscription slots per transport (one per subscribable resource) */
#define API2_SUB_SLOTS 23U

extern const ApiCategory g_api_categories[];
extern const uint8_t g_api_category_count;

#endif /* SVC_API_DEFS_H */
