/* GENERATED by tools/gen_api.py from tools/api_spec.py -- do not edit; edit the spec and regenerate. */
#include "svc_api_defs.h"
#include "system_state.h"
#include <stddef.h>

static const ApiFieldDesc k_fields_calibrations[] = {
    { API2_RES_CALIBRATIONS_S1_K, 4, true, offsetof(DeviceSettings, disp_s1_k_micro), 100LL, 1000000LL, 0, 0, false },  /* S1_K */
    { API2_RES_CALIBRATIONS_S1_ZERO, 4, true, offsetof(DeviceSettings, disp_s1_zero_ppm), -500000LL, 500000LL, 0, 0, false },  /* S1_ZERO */
    { API2_RES_CALIBRATIONS_S1_PHASE, 2, true, offsetof(DeviceSettings, disp_s1_phase_cdeg), -4500LL, 4500LL, 0, 0, false },  /* S1_PHASE */
    { API2_RES_CALIBRATIONS_S1_INVERT, 1, false, offsetof(DeviceSettings, disp_s1_invert), 0LL, 1LL, 0, 0, false },  /* S1_INVERT */
    { API2_RES_CALIBRATIONS_S2_K, 4, true, offsetof(DeviceSettings, disp_s2_k_micro), 100LL, 1000000LL, 0, 0, false },  /* S2_K */
    { API2_RES_CALIBRATIONS_S2_ZERO, 4, true, offsetof(DeviceSettings, disp_s2_zero_ppm), -500000LL, 500000LL, 0, 0, false },  /* S2_ZERO */
    { API2_RES_CALIBRATIONS_S2_PHASE, 2, true, offsetof(DeviceSettings, disp_s2_phase_cdeg), -4500LL, 4500LL, 0, 0, false },  /* S2_PHASE */
    { API2_RES_CALIBRATIONS_S2_INVERT, 1, false, offsetof(DeviceSettings, disp_s2_invert), 0LL, 1LL, 0, 0, false },  /* S2_INVERT */
    { API2_RES_CALIBRATIONS_VBAT_SCALE_NUM, 2, false, offsetof(DeviceSettings, vbat_scale_num), 1LL, 10000LL, 0, 0, false },  /* VBAT_SCALE_NUM */
    { API2_RES_CALIBRATIONS_VBAT_SCALE_DEN, 2, false, offsetof(DeviceSettings, vbat_scale_den), 1LL, 10000LL, 0, 0, false },  /* VBAT_SCALE_DEN */
    { API2_RES_CALIBRATIONS_VBAT_OFFSET, 4, true, offsetof(DeviceSettings, vbat_offset_mv), -500LL, 500LL, 0, 0, false },  /* VBAT_OFFSET */
    { API2_RES_CALIBRATIONS_TMP236_SEG1_VOFFS, 2, false, offsetof(DeviceSettings, tmp236_seg1_voffs_mv), 0LL, 3300LL, 0, 0, false },  /* TMP236_SEG1_VOFFS */
    { API2_RES_CALIBRATIONS_TMP236_SEG1_NUM, 2, false, offsetof(DeviceSettings, tmp236_seg1_num), 1LL, 10000LL, 0, 0, false },  /* TMP236_SEG1_NUM */
    { API2_RES_CALIBRATIONS_TMP236_SEG1_DEN, 2, false, offsetof(DeviceSettings, tmp236_seg1_den), 1LL, 10000LL, 0, 0, false },  /* TMP236_SEG1_DEN */
    { API2_RES_CALIBRATIONS_TMP236_SEG_BOUNDARY, 2, false, offsetof(DeviceSettings, tmp236_seg_boundary_mv), 0LL, 3300LL, 0, 0, false },  /* TMP236_SEG_BOUNDARY */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_VOFFS, 2, false, offsetof(DeviceSettings, tmp236_seg2_voffs_mv), 0LL, 3300LL, 0, 0, false },  /* TMP236_SEG2_VOFFS */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_NUM, 2, false, offsetof(DeviceSettings, tmp236_seg2_num), 1LL, 10000LL, 0, 0, false },  /* TMP236_SEG2_NUM */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_DEN, 2, false, offsetof(DeviceSettings, tmp236_seg2_den), 1LL, 10000LL, 0, 0, false },  /* TMP236_SEG2_DEN */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_TINFL, 2, false, offsetof(DeviceSettings, tmp236_seg2_tinfl_cdeg), 0LL, 20000LL, 0, 0, false },  /* TMP236_SEG2_TINFL */
    { API2_RES_CALIBRATIONS_LM35_SCALE, 2, false, offsetof(DeviceSettings, lm35_scale_mv_per_c), 1LL, 1000LL, 0, 0, false },  /* LM35_SCALE */
    { API2_RES_CALIBRATIONS_RTC_TRIM, 2, true, offsetof(DeviceSettings, rtc_trim_ppm_x10), -4800LL, 4800LL, 0, api_after_rtc_trim, false },  /* RTC_TRIM */
};

static const ApiFieldDesc k_fields_settings[] = {
    { API2_RES_SETTINGS_TASK_SENSORS, 2, false, offsetof(DeviceSettings, task_sensors_ms), 1LL, 1000LL, 0, 0, true },  /* TASK_SENSORS */
    { API2_RES_SETTINGS_TASK_BLE, 2, false, offsetof(DeviceSettings, task_ble_ms), 1LL, 250LL, 0, 0, true },  /* TASK_BLE */
    { API2_RES_SETTINGS_TASK_USB, 2, false, offsetof(DeviceSettings, task_usb_ms), 1LL, 250LL, 0, 0, true },  /* TASK_USB */
    { API2_RES_SETTINGS_TASK_BATTERY, 2, false, offsetof(DeviceSettings, task_battery_ms), 100LL, 10000LL, 0, 0, true },  /* TASK_BATTERY */
    { API2_RES_SETTINGS_TASK_TEMPERATURE, 2, false, offsetof(DeviceSettings, task_temperature_ms), 100LL, 60000LL, 0, 0, true },  /* TASK_TEMPERATURE */
    { API2_RES_SETTINGS_BATTERY_CRITICAL, 2, false, offsetof(DeviceSettings, battery_critical_mv), 2500LL, 3600LL, api_check_battery_order, 0, true },  /* BATTERY_CRITICAL */
    { API2_RES_SETTINGS_BATTERY_LOW, 2, false, offsetof(DeviceSettings, battery_low_mv), 3000LL, 4200LL, api_check_battery_order, 0, true },  /* BATTERY_LOW */
    { API2_RES_SETTINGS_BATTERY_CHARGE_START, 2, false, offsetof(DeviceSettings, battery_charge_start_mv), 3000LL, 4200LL, 0, 0, true },  /* BATTERY_CHARGE_START */
    { API2_RES_SETTINGS_AUTO_POWEROFF, 2, false, offsetof(DeviceSettings, auto_poweroff_s), 0LL, 65535LL, 0, 0, true },  /* AUTO_POWEROFF */
    { API2_RES_SETTINGS_ENCODER_COUNTS_PER_DETENT, 2, false, offsetof(DeviceSettings, encoder_counts_per_detent), 1LL, 100LL, 0, 0, true },  /* ENCODER_COUNTS_PER_DETENT */
};

static const ApiResource k_res_system[] = {
    { API2_RES_SYSTEM_IDENTITY, API2_VERB_BIT(API2_VERB_GET), API2_SUB_NONE, 4, 0, 0, api_h_system_identity, 0, 0, 0, 1, 0 },  /* IDENTITY */
    { API2_RES_SYSTEM_STATE, API2_VERB_BIT(API2_VERB_GET), API2_SUB_NONE, 4, 0, 0, api_h_system_state, 0, 0, 0, 1, 0 },  /* STATE */
    { API2_RES_SYSTEM_HEALTH, API2_VERB_BIT(API2_VERB_GET), API2_SUB_NONE, 4, 0, 0, api_h_system_health, 0, 0, 0, 1, 0 },  /* HEALTH */
    { API2_RES_SYSTEM_RTC, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 7, 7, api_h_system_rtc, 0, 0, 0, 1, 0 },  /* RTC */
};

static const ApiResource k_res_commands[] = {
    { API2_RES_COMMANDS_POWER_OFF, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_power_off, 0, 0, 0, 1, 0 },  /* POWER_OFF */
    { API2_RES_COMMANDS_REBOOT, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_reboot, 0, 0, 0, 1, 0 },  /* REBOOT */
    { API2_RES_COMMANDS_REBOOT_DFU, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_reboot_dfu, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* REBOOT_DFU */
    { API2_RES_COMMANDS_FORCE_CHARGE, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_force_charge, 0, 0, 0, 1, 0 },  /* FORCE_CHARGE */
    { API2_RES_COMMANDS_END_CHARGING, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_end_charging, 0, 0, 0, 1, 0 },  /* END_CHARGING */
    { API2_RES_COMMANDS_CHARGE_INHIBIT, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 1, api_h_commands_charge_inhibit, 0, 0, 0, 1, 0 },  /* CHARGE_INHIBIT */
    { API2_RES_COMMANDS_DISPLACEMENT, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 1, api_h_commands_displacement, 0, 0, 0, 1, 0 },  /* DISPLACEMENT */
    { API2_RES_COMMANDS_ZERO_CAL, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 2, api_h_commands_zero_cal, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* ZERO_CAL */
    { API2_RES_COMMANDS_PRECISION, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 1, api_h_commands_precision, 0, 0, 0, 1, 0 },  /* PRECISION */
    { API2_RES_COMMANDS_FACTORY_DEFAULTS, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 1, api_h_commands_factory_defaults, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* FACTORY_DEFAULTS */
    { API2_RES_COMMANDS_SERVICE_END, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_service_end, 0, 0, 0, 1, 0 },  /* SERVICE_END */
    { API2_RES_COMMANDS_CLEAR_COUNTERS, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_clear_counters, 0, 0, 0, 1, 0 },  /* CLEAR_COUNTERS */
    { API2_RES_COMMANDS_TEST_BEEP, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 0, 0, api_h_commands_test_beep, 0, 0, 0, 1, 0 },  /* TEST_BEEP */
    { API2_RES_COMMANDS_POWER_TEST, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 4, 4, api_h_commands_power_test, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* POWER_TEST */
    { API2_RES_COMMANDS_PIN_TEST, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 1, api_h_commands_pin_test, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* PIN_TEST */
    { API2_RES_COMMANDS_FAULT_TEST, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 1, 1, api_h_commands_fault_test, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* FAULT_TEST */
    { API2_RES_COMMANDS_RAIL, API2_VERB_BIT(API2_VERB_EXECUTE), API2_SUB_NONE, 4, 2, 2, api_h_commands_rail, 0, 0, 0, 1, API2_RES_F_SERVICE },  /* RAIL */
};

static const ApiResource k_res_calibrations[] = {
    { API2_RES_CALIBRATIONS_S1_K, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 4, 4, api_field_handler, 0, &k_fields_calibrations[0], 0, 1, API2_RES_F_SERVICE },  /* S1_K */
    { API2_RES_CALIBRATIONS_S1_ZERO, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 4, 4, api_field_handler, 0, &k_fields_calibrations[1], 0, 1, API2_RES_F_SERVICE },  /* S1_ZERO */
    { API2_RES_CALIBRATIONS_S1_PHASE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[2], 0, 1, API2_RES_F_SERVICE },  /* S1_PHASE */
    { API2_RES_CALIBRATIONS_S1_INVERT, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 1, 1, api_field_handler, 0, &k_fields_calibrations[3], 0, 1, API2_RES_F_SERVICE },  /* S1_INVERT */
    { API2_RES_CALIBRATIONS_S2_K, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 4, 4, api_field_handler, 0, &k_fields_calibrations[4], 0, 1, API2_RES_F_SERVICE },  /* S2_K */
    { API2_RES_CALIBRATIONS_S2_ZERO, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 4, 4, api_field_handler, 0, &k_fields_calibrations[5], 0, 1, API2_RES_F_SERVICE },  /* S2_ZERO */
    { API2_RES_CALIBRATIONS_S2_PHASE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[6], 0, 1, API2_RES_F_SERVICE },  /* S2_PHASE */
    { API2_RES_CALIBRATIONS_S2_INVERT, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 1, 1, api_field_handler, 0, &k_fields_calibrations[7], 0, 1, API2_RES_F_SERVICE },  /* S2_INVERT */
    { API2_RES_CALIBRATIONS_VBAT_SCALE_NUM, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[8], 0, 1, API2_RES_F_SERVICE },  /* VBAT_SCALE_NUM */
    { API2_RES_CALIBRATIONS_VBAT_SCALE_DEN, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[9], 0, 1, API2_RES_F_SERVICE },  /* VBAT_SCALE_DEN */
    { API2_RES_CALIBRATIONS_VBAT_OFFSET, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 4, 4, api_field_handler, 0, &k_fields_calibrations[10], 0, 1, API2_RES_F_SERVICE },  /* VBAT_OFFSET */
    { API2_RES_CALIBRATIONS_TMP236_SEG1_VOFFS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[11], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG1_VOFFS */
    { API2_RES_CALIBRATIONS_TMP236_SEG1_NUM, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[12], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG1_NUM */
    { API2_RES_CALIBRATIONS_TMP236_SEG1_DEN, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[13], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG1_DEN */
    { API2_RES_CALIBRATIONS_TMP236_SEG_BOUNDARY, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[14], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG_BOUNDARY */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_VOFFS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[15], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG2_VOFFS */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_NUM, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[16], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG2_NUM */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_DEN, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[17], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG2_DEN */
    { API2_RES_CALIBRATIONS_TMP236_SEG2_TINFL, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[18], 0, 1, API2_RES_F_SERVICE },  /* TMP236_SEG2_TINFL */
    { API2_RES_CALIBRATIONS_LM35_SCALE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[19], 0, 1, API2_RES_F_SERVICE },  /* LM35_SCALE */
    { API2_RES_CALIBRATIONS_RTC_TRIM, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_calibrations[20], 0, 1, API2_RES_F_SERVICE },  /* RTC_TRIM */
};

static const ApiResource k_res_settings[] = {
    { API2_RES_SETTINGS_TASK_SENSORS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[0], 0, 1, 0 },  /* TASK_SENSORS */
    { API2_RES_SETTINGS_TASK_BLE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[1], 0, 1, 0 },  /* TASK_BLE */
    { API2_RES_SETTINGS_TASK_USB, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[2], 0, 1, 0 },  /* TASK_USB */
    { API2_RES_SETTINGS_TASK_BATTERY, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[3], 0, 1, 0 },  /* TASK_BATTERY */
    { API2_RES_SETTINGS_TASK_TEMPERATURE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[4], 0, 1, 0 },  /* TASK_TEMPERATURE */
    { API2_RES_SETTINGS_BATTERY_CRITICAL, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[5], 0, 1, 0 },  /* BATTERY_CRITICAL */
    { API2_RES_SETTINGS_BATTERY_LOW, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[6], 0, 1, 0 },  /* BATTERY_LOW */
    { API2_RES_SETTINGS_BATTERY_CHARGE_START, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[7], 0, 1, 0 },  /* BATTERY_CHARGE_START */
    { API2_RES_SETTINGS_AUTO_POWEROFF, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[8], 0, 1, 0 },  /* AUTO_POWEROFF */
    { API2_RES_SETTINGS_ENCODER_COUNTS_PER_DETENT, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), API2_SUB_NONE, 4, 2, 2, api_field_handler, 0, &k_fields_settings[9], 0, 1, 0 },  /* ENCODER_COUNTS_PER_DETENT */
};

static const ApiResource k_res_measurements[] = {
    { API2_RES_MEASUREMENTS_ONBOARD_TEMP, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_onboard_temp, 0, 0, 0, 1, 0 },  /* ONBOARD_TEMP */
    { API2_RES_MEASUREMENTS_BATTERY_MV, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_battery_mv, 0, 0, 1, 1, 0 },  /* BATTERY_MV */
    { API2_RES_MEASUREMENTS_BATTERY_SOC, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_battery_soc, 0, 0, 2, 1, 0 },  /* BATTERY_SOC */
    { API2_RES_MEASUREMENTS_BME_TEMP, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_bme_temp, 0, 0, 3, 1, 0 },  /* BME_TEMP */
    { API2_RES_MEASUREMENTS_BME_PRESSURE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_bme_pressure, 0, 0, 4, 1, 0 },  /* BME_PRESSURE */
    { API2_RES_MEASUREMENTS_BME_HUMIDITY, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_bme_humidity, 0, 0, 5, 1, 0 },  /* BME_HUMIDITY */
    { API2_RES_MEASUREMENTS_BME_OK, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_bme_ok, 0, 0, 6, 1, 0 },  /* BME_OK */
    { API2_RES_MEASUREMENTS_EXT_TEMP, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_ext_temp, 0, 0, 7, 1, 0 },  /* EXT_TEMP */
    { API2_RES_MEASUREMENTS_EXT_TEMP_OK, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_ext_temp_ok, 0, 0, 8, 1, 0 },  /* EXT_TEMP_OK */
    { API2_RES_MEASUREMENTS_TILT_S1, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_tilt_s1, 0, 0, 9, 1, 0 },  /* TILT_S1 */
    { API2_RES_MEASUREMENTS_TILT_S2, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_tilt_s2, 0, 0, 10, 1, 0 },  /* TILT_S2 */
    { API2_RES_MEASUREMENTS_TILT_DIFF, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_tilt_diff, 0, 0, 11, 1, 0 },  /* TILT_DIFF */
    { API2_RES_MEASUREMENTS_TILT_FLAGS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_tilt_flags, 0, 0, 12, 1, 0 },  /* TILT_FLAGS */
    { API2_RES_MEASUREMENTS_TILT_SEQ, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_measurements_tilt_seq, 0, 0, 13, 1, 0 },  /* TILT_SEQ */
};

static const ApiResource k_res_topics[] = {
    { API2_RES_TOPICS_ENV, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_topics_env, 0, 0, 14, 1, 0 },  /* ENV */
    { API2_RES_TOPICS_STATUS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_topics_status, 0, 0, 15, 1, 0 },  /* STATUS */
    { API2_RES_TOPICS_LIVE, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_EVENT, 4, 0, 0, api_h_topics_live, &api_ev_live, 0, 16, 1, 0 },  /* LIVE */
    { API2_RES_TOPICS_RAW, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_topics_raw, 0, 0, 17, 1, 0 },  /* RAW */
    { API2_RES_TOPICS_PHASOR_STREAM, API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_EVENT, 4, 0, 0, api_h_topics_phasor_stream, &api_ev_phasor_stream, 0, 18, 4, 0 },  /* PHASOR_STREAM */
    { API2_RES_TOPICS_SIGNAL_DIAG, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_INTERVAL, 4, 0, 0, api_h_topics_signal_diag, 0, 0, 19, 1, 0 },  /* SIGNAL_DIAG */
};

static const ApiResource k_res_debug[] = {
    { API2_RES_DEBUG_LOG, API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_EVENT, 1, 0, 0, api_h_debug_log, &api_ev_log, 0, 20, 4, 0 },  /* LOG */
};

static const ApiResource k_res_diagnostics[] = {
    { API2_RES_DIAGNOSTICS_ADC, API2_VERB_BIT(API2_VERB_GET), API2_SUB_NONE, 4, 0, 0, api_h_diagnostics_adc, 0, 0, 0, 1, 0 },  /* ADC */
    { API2_RES_DIAGNOSTICS_POWER, API2_VERB_BIT(API2_VERB_GET), API2_SUB_NONE, 4, 0, 0, api_h_diagnostics_power, 0, 0, 0, 1, 0 },  /* POWER */
    { API2_RES_DIAGNOSTICS_DISPLACEMENT, API2_VERB_BIT(API2_VERB_GET), API2_SUB_NONE, 4, 0, 0, api_h_diagnostics_displacement, 0, 0, 0, 1, 0 },  /* DISPLACEMENT */
};

static const ApiResource k_res_bulk[] = {
    { API2_RES_BULK_RAW_ADC, API2_VERB_BIT(API2_VERB_START_BULK) | API2_VERB_BIT(API2_VERB_CANCEL_BULK), API2_SUB_NONE, 4, 0, 0, api_h_bulk_raw_adc, 0, 0, 0, 1, 0 },  /* RAW_ADC */
};

static const ApiResource k_res_procedures[] = {
    { API2_RES_PROCEDURES_ZERO_CAL, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_EVENT, 4, 0, 0, api_h_procedures_zero_cal, &api_ev_zero_cal, 0, 21, 1, 0 },  /* ZERO_CAL */
    { API2_RES_PROCEDURES_PRECISION, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), API2_SUB_EVENT, 4, 0, 0, api_h_procedures_precision, &api_ev_precision, 0, 22, 1, 0 },  /* PRECISION */
};

const ApiCategory g_api_categories[] = {
    { API2_CAT_SYSTEM, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), k_res_system, (uint8_t)(sizeof k_res_system / sizeof k_res_system[0]) },
    { API2_CAT_COMMANDS, API2_VERB_BIT(API2_VERB_EXECUTE), k_res_commands, (uint8_t)(sizeof k_res_commands / sizeof k_res_commands[0]) },
    { API2_CAT_CALIBRATIONS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), k_res_calibrations, (uint8_t)(sizeof k_res_calibrations / sizeof k_res_calibrations[0]) },
    { API2_CAT_SETTINGS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SET), k_res_settings, (uint8_t)(sizeof k_res_settings / sizeof k_res_settings[0]) },
    { API2_CAT_MEASUREMENTS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), k_res_measurements, (uint8_t)(sizeof k_res_measurements / sizeof k_res_measurements[0]) },
    { API2_CAT_TOPICS, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), k_res_topics, (uint8_t)(sizeof k_res_topics / sizeof k_res_topics[0]) },
    { API2_CAT_DEBUG, API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), k_res_debug, (uint8_t)(sizeof k_res_debug / sizeof k_res_debug[0]) },
    { API2_CAT_DIAGNOSTICS, API2_VERB_BIT(API2_VERB_GET), k_res_diagnostics, (uint8_t)(sizeof k_res_diagnostics / sizeof k_res_diagnostics[0]) },
    { API2_CAT_BULK, API2_VERB_BIT(API2_VERB_START_BULK) | API2_VERB_BIT(API2_VERB_CANCEL_BULK), k_res_bulk, (uint8_t)(sizeof k_res_bulk / sizeof k_res_bulk[0]) },
    { API2_CAT_PROCEDURES, API2_VERB_BIT(API2_VERB_GET) | API2_VERB_BIT(API2_VERB_SUBSCRIBE) | API2_VERB_BIT(API2_VERB_UNSUBSCRIBE), k_res_procedures, (uint8_t)(sizeof k_res_procedures / sizeof k_res_procedures[0]) },
};
const uint8_t g_api_category_count = (uint8_t)(sizeof g_api_categories / sizeof g_api_categories[0]);
