#!/usr/bin/env python3
"""Generates the API definitions from tools/api_spec.py.  See the docstring there.

  python tools/gen_api.py            write the generated files
  python tools/gen_api.py --check    exit 1 if a committed generated file differs from what the spec produces
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import api_spec as S  # noqa: E402

BANNER = "GENERATED by tools/gen_api.py from tools/api_spec.py -- do not edit; edit the spec and regenerate."

CTYPE = {"u8": "uint8_t", "i8": "int8_t", "u16": "uint16_t", "i16": "int16_t", "u32": "uint32_t",
         "i32": "int32_t", "f32": "float"}
PYFMT = {"u8": "B", "i8": "b", "u16": "H", "i16": "h", "u32": "I", "i32": "i", "f32": "f"}
SIZE = {"u8": 1, "i8": 1, "u16": 2, "i16": 2, "u32": 4, "i32": 4, "f32": 4}


def char_len(t):
    m = re.fullmatch(r"char\[(\d+)\]", t)
    return int(m.group(1)) if m else None


def tsize(t):
    n = char_len(t)
    return n if n is not None else SIZE[t]


def fields_size(fields):
    return sum(tsize(f.ctype) for f in fields)


def has_tail(fields):
    return any(char_len(f.ctype) == 0 for f in fields)


def camel(name):
    return "".join(p.capitalize() for p in name.lower().split("_"))


def cat_c(cat):
    return cat.name


def res_c(r):
    return "API2_RES_%s_%s" % (r.cat.name, r.name)


def verb_bit(v):
    return "API2_VERB_BIT(API2_VERB_%s)" % v


def mask_expr(verbs):
    return " | ".join(verb_bit(v) for v in verbs)


def struct_name(r, role):
    return "Api2%s%s%s" % (camel(r.cat.name), camel(r.name), role)


def handler_name(r):
    return "api_h_%s_%s" % (r.cat.name.lower(), r.name.lower())


def roles(r):
    """(role, fields) of every payload this resource has."""
    out = []
    if r.kind == "field":
        return [("Value", r.rsp)]
    if r.rsp is not None:
        out.append(("Response", r.rsp))
    if r.req:
        out.append(("Request", r.req))
    if r.push is not None:
        out.append(("Push", r.push))
    elif r.sub == "event" and r.rsp is not None:
        pass
    if r.sub_req:
        out.append(("Subscribe", r.sub_req))
    return out


def all_resources():
    for c in S.CATEGORIES:
        for r in c.resources:
            yield c, r


def check_spec():
    seen = set()
    for c in S.CATEGORIES:
        assert c.id not in seen, "duplicate category id"
        seen.add(c.id)
        ids = set()
        for r in c.resources:
            assert r.id not in ids, "duplicate resource id %s %s" % (c.name, r.name)
            ids.add(r.id)
            for v in r.verbs:
                assert v in c.verbs, "%s.%s: verb %s not allowed in category" % (c.name, r.name, v)
            if "EXECUTE" in r.verbs or "SET" in r.verbs:
                assert r.id >= 0x40 or c.name in ("SYSTEM",), "state-changing %s.%s below 0x40" % (c.name, r.name)
            if r.sub:
                assert "SUBSCRIBE" in r.verbs and "UNSUBSCRIBE" in r.verbs
            if r.sub == "event":
                assert r.ev, "event resource %s needs ev=" % r.name
            for role, fl in roles(r):
                if not has_tail(fl):
                    sz = fields_size(fl)
                    lim = S.MAX_PAYLOAD - 1 - (S.PUSH_PREFIX if role == "Push" or r.sub else 0)
                    if role == "Request":
                        lim = S.MAX_PAYLOAD
                    assert sz <= lim, "%s.%s %s payload %d B > %d" % (c.name, r.name, role, sz, lim)


def req_range(r):
    if r.req_len is not None:
        return r.req_len
    if r.kind == "field":
        n = tsize(r.ctype)
        return (n, n)
    if r.req is not None:
        n = fields_size(r.req)
        return (n, n)
    return (0, 0)


def sub_in_len(r):
    if r.sub_req is not None:
        return fields_size(r.sub_req)
    return 4


# ----------------------------------------------------------------------------------------------------------- C header
def gen_defs_h():
    o = []
    w = o.append
    w("/* %s */\n" % BANNER)
    w("#ifndef SVC_API_DEFS_H\n#define SVC_API_DEFS_H\n\n#include <stdint.h>\n#include <stdbool.h>\n")
    w('#include "svc_api_core.h"\n\n')
    w("#define API2_VERSION      %dU\n" % S.API_VERSION)
    w("#define API2_MAX_PAYLOAD  %dU\n\n" % S.MAX_PAYLOAD)
    w("/* categories */\n")
    for c in S.CATEGORIES:
        w("#define API2_CAT_%-14s 0x%XU\n" % (c.name, c.id))
    w("\n/* resource ids */\n")
    for c, r in all_resources():
        w("#define %-44s 0x%02XU\n" % (res_c(r), r.id))
    w("\n/* opcodes: API2_OP_<CATEGORY>_<RESOURCE>_<VERB> */\n")
    for c, r in all_resources():
        for v in r.verbs:
            w("#define API2_OP_%s_%s_%-12s API2_OPCODE(API2_VERB_%s, API2_CAT_%s, %s)\n"
              % (c.name, r.name, v, v, c.name, res_c(r)))
    w("\n/* wire payloads (after the status byte / after [issue_seq][page] for pushes); packed, little-endian */\n")
    for c, r in all_resources():
        for role, fl in roles(r):
            if has_tail(fl) or not fl:
                continue
            sn = struct_name(r, role)
            w("typedef struct {\n")
            for f in fl:
                n = char_len(f.ctype)
                if n is not None:
                    w("    char     %s[%d];\n" % (f.name, n))
                else:
                    w("    %-8s %s;\n" % (CTYPE[f.ctype], f.name))
            w("} __attribute__((packed)) %s;\n" % sn)
            sz = fields_size(fl)
            w("_Static_assert(sizeof(%s) == %dU, \"%s layout\");\n" % (sn, sz, sn))
    w("\n/* handlers: implemented in Services/svc_api_res_*.c; field resources use api_field_handler */\n")
    for c, r in all_resources():
        if r.kind != "field":
            w("Api2Status %s(const ApiResource *r, ApiCall *c);\n" % handler_name(r))
    evs = sorted({r.ev for _, r in all_resources() if r.ev})
    if evs:
        w("\n/* event-subscription operations */\n")
        for e in evs:
            w("extern const ApiEventOps api_ev_%s;\n" % e)
    checks = sorted({r.check for _, r in all_resources() if r.kind == "field" and r.check})
    afters = sorted({r.after for _, r in all_resources() if r.kind == "field" and r.after})
    if checks or afters:
        w("\n/* hooks of field resources */\n")
        for k in checks:
            w("bool api_check_%s(uint8_t res, int64_t value);\n" % k)
        for k in afters:
            w("void api_after_%s(void);\n" % k)
    slots = sum(1 for _, r in all_resources() if r.sub)
    w("\n/* subscription slots per transport (one per subscribable resource) */\n")
    w("#define API2_SUB_SLOTS %dU\n" % slots)
    w("\nextern const ApiCategory g_api_categories[];\nextern const uint8_t g_api_category_count;\n")
    w("\n#endif /* SVC_API_DEFS_H */\n")
    return "".join(o)


# ----------------------------------------------------------------------------------------------------------- C tables
def gen_tables_c():
    o = []
    w = o.append
    w("/* %s */\n" % BANNER)
    w('#include "svc_api_defs.h"\n#include "system_state.h"\n#include <stddef.h>\n\n')
    # field descriptor arrays
    for c in S.CATEGORIES:
        frs = [r for r in c.resources if r.kind == "field"]
        if not frs:
            continue
        w("static const ApiFieldDesc k_fields_%s[] = {\n" % c.name.lower())
        for r in frs:
            signed = "true" if r.ctype.startswith("i") else "false"
            chk = "api_check_%s" % r.check if r.check else "0"
            aft = "api_after_%s" % r.after if r.after else "0"
            notify = "true" if c.name == "SETTINGS" else "false"
            w("    { %s, %d, %s, offsetof(DeviceSettings, %s), %dLL, %dLL, %s, %s, %s },  /* %s */\n"
              % (res_c(r), tsize(r.ctype), signed, r.field, r.lo, r.hi, chk, aft, notify, r.name))
        w("};\n\n")
    # forward decl of handlers is in the header; field handler from core
    slot = 0
    for c in S.CATEGORIES:
        w("static const ApiResource k_res_%s[] = {\n" % c.name.lower())
        fidx = 0
        for r in c.resources:
            lo, hi = req_range(r)
            sub = {"interval": "API2_SUB_INTERVAL", "event": "API2_SUB_EVENT"}.get(r.sub, "API2_SUB_NONE")
            s = slot if r.sub else 0
            if r.sub:
                slot += 1
            ev = "&api_ev_%s" % r.ev if r.ev else "0"
            if r.kind == "field":
                h = "api_field_handler"
                ctx = "&k_fields_%s[%d]" % (c.name.lower(), fidx)
                fidx += 1
            else:
                h = handler_name(r)
                ctx = "0"
            burst = 4 if (r.ev in ("phasor_stream", "log")) else 1
            flags = "API2_RES_F_SERVICE" if r.service else "0"
            w("    { %s, %s, %s, %d, %d, %d, %s, %s, %s, %d, %d, %s },  /* %s */\n"
              % (res_c(r), mask_expr(r.verbs), sub, sub_in_len(r), lo, hi, h, ev, ctx, s, burst, flags, r.name))
        w("};\n\n")
    w("const ApiCategory g_api_categories[] = {\n")
    for c in S.CATEGORIES:
        w("    { API2_CAT_%s, %s, k_res_%s, (uint8_t)(sizeof k_res_%s / sizeof k_res_%s[0]) },\n"
          % (c.name, mask_expr(c.verbs), c.name.lower(), c.name.lower(), c.name.lower()))
    w("};\nconst uint8_t g_api_category_count = (uint8_t)(sizeof g_api_categories / sizeof g_api_categories[0]);\n")
    return "".join(o)


# ----------------------------------------------------------------------------------------------------------- test stubs
def gen_stubs_inc():
    """Do-nothing handlers for every non-field resource, so the real tables link on the host (tests/test_api_tables.c)."""
    NL = chr(10)
    o = []
    w = o.append
    w("/* %s */" % BANNER + NL)
    w("/* included by tests/test_api_tables.c: counts the calls, answers OK */" + NL)
    w("static unsigned g_stub_calls;" + NL + "static uint8_t g_stub_last_verb;" + NL + "static uint8_t g_stub_last_res;" + NL)
    for c, r in all_resources():
        if r.kind != "field":
            w("Api2Status %s(const ApiResource *r, ApiCall *c) { (void)r; g_stub_calls++; g_stub_last_verb = c->verb; "
              "g_stub_last_res = c->res; return API2_STATUS_OK; }" % handler_name(r) + NL)
    for e in sorted({r.ev for _, r in all_resources() if r.ev}):
        w("static Api2Status stub_%s_start(const ApiResource *r, ApiTransport t, ApiSub *s, const uint8_t *in, uint16_t n)"
          " { (void)r; (void)t; (void)s; (void)in; (void)n; return API2_STATUS_OK; }" % e + NL)
        w("const ApiEventOps api_ev_%s = { stub_%s_start, 0, 0 };" % (e, e) + NL)
    return "".join(o)


# ----------------------------------------------------------------------------------------------------------- Python
def gen_py():
    o = []
    w = o.append
    w('"""%s"""\n' % BANNER)
    w("import struct\n\n")
    w("API_VERSION = %d\nMAX_PAYLOAD = %d\n\n" % (S.API_VERSION, S.MAX_PAYLOAD))
    w("VERBS = {%s}\n" % ", ".join('"%s": %d' % (k, v) for k, v in S.VERB_VALUE.items()))
    for k, v in S.VERB_VALUE.items():
        w("%s = %d\n" % (k, v))
    w("\n")
    for c in S.CATEGORIES:
        w("CAT_%s = 0x%X\n" % (c.name, c.id))
    w("\n\ndef opcode(verb, cat, res):\n    return ((verb & 0xF) << 12) | ((cat & 0xF) << 8) | (res & 0xFF)\n\n\n")
    for c, r in all_resources():
        w("RES_%s_%s = 0x%02X\n" % (c.name, r.name, r.id))
    w("\n")
    for c, r in all_resources():
        for v in r.verbs:
            w("OP_%s_%s_%s = opcode(%s, CAT_%s, RES_%s_%s)\n" % (c.name, r.name, v, v, c.name, c.name, r.name))
    w("\n\n")
    for c, r in all_resources():
        for role, fl in roles(r):
            if not fl and role != "Response":
                continue
            base = "%s_%s_%s" % (c.name.lower(), r.name.lower(), role.lower())
            tail = has_tail(fl)
            fixed = [f for f in fl if char_len(f.ctype) != 0]
            fmt = "<" + "".join(("%ds" % char_len(f.ctype)) if char_len(f.ctype) is not None else PYFMT[f.ctype]
                                for f in fixed)
            w("FMT_%s = %r\nSIZE_%s = struct.calcsize(FMT_%s)\nFIELDS_%s = (%s)\n"
              % (base.upper(), fmt, base.upper(), base.upper(), base.upper(),
                 "".join("%r, " % f.name for f in fixed)))
            w("def decode_%s(data):\n" % base)
            w("    if len(data) < SIZE_%s:\n        return None\n" % base.upper())
            w("    v = struct.unpack_from(FMT_%s, data)\n    d = dict(zip(FIELDS_%s, v))\n" % (base.upper(), base.upper()))
            w("    for k, x in d.items():\n        if isinstance(x, bytes):\n"
              "            d[k] = x.split(b'\\0', 1)[0].decode('ascii', 'replace')\n")
            if tail:
                tn = [f.name for f in fl if char_len(f.ctype) == 0][0]
                w("    d[%r] = data[SIZE_%s:].decode('ascii', 'replace')\n" % (tn, base.upper()))
            w("    return d\n\n")
            if role in ("Request", "Subscribe") and not tail:
                args = ", ".join(f.name for f in fixed)
                w("def encode_%s(%s):\n    return struct.pack(FMT_%s, %s)\n\n"
                  % (base, args, base.upper(), args))
    # convenience tables for field resources
    for c in S.CATEGORIES:
        frs = [r for r in c.resources if r.kind == "field"]
        if not frs:
            continue
        w("%s = {  # name -> (resource id, struct format, lo, hi, unit)\n" % c.name)
        for r in frs:
            w("    %r: (RES_%s_%s, '<%s', %d, %d, %r),\n" % (r.name, c.name, r.name, PYFMT[r.ctype], r.lo, r.hi, r.unit))
        w("}\n\n")
    return "".join(o).rstrip("\n") + "\n"


# ----------------------------------------------------------------------------------------------------------- docs
def md_fields(fl, with_off=True):
    rows = ["| Offset | Type | Field | Unit | Meaning |", "|---:|---|---|---|---|"]
    off = 0
    for f in fl:
        n = char_len(f.ctype)
        t = ("char[%d]" % n) if n else f.ctype
        if n == 0:
            t, o_ = "char[]", "%d.." % off
        else:
            o_ = str(off)
            off += tsize(f.ctype)
        rows.append("| %s | %s | `%s` | %s | %s |" % (o_, t, f.name, f.unit, f.doc))
    return "\n".join(rows)


def gen_md():
    o = []
    w = o.append
    w("<!-- %s -->\n" % BANNER)
    w("# Device API v%d -- reference\n\n" % S.API_VERSION)
    w("Generated from `tools/api_spec.py`. The protocol itself (framing, verbs, status codes, dispatch order, "
      "subscriptions, bulk transfers, the transports) is described in [api-v3-spec.md](api-v3-spec.md); this page lists "
      "every resource.\n\n")
    w("Opcode = `[verb:4][category:4][resource:8]`, little-endian on the wire. Every response payload starts with a "
      "status byte; the tables below describe what follows an OK status. Little-endian, IEEE-754 floats. "
      "Largest payload: %d bytes.\n\n" % S.MAX_PAYLOAD)
    w("| Cat | Name | Verbs | What |\n|---:|---|---|---|\n")
    for c in S.CATEGORIES:
        w("| 0x%X | [%s](#%s) | %s | %s |\n" % (c.id, c.title, c.title.lower().replace(" ", "-"),
                                              ", ".join(c.verbs), c.doc.split(". ")[0].rstrip(".") + "."))
    w("\n")
    for c in S.CATEGORIES:
        w("## %s\n\nCategory 0x%X. Verbs: %s.\n\n%s\n\n" % (c.title, c.id, ", ".join(c.verbs), c.doc))
        w("| ID | Name | Verbs | Notes |\n|---:|---|---|---|\n")
        for r in c.resources:
            note = r.doc.split(". ")[0].rstrip(".")
            if r.kind == "field":
                note = "%s [%d .. %d%s]" % (note, r.lo, r.hi, (" " + r.unit) if r.unit else "")
            w("| 0x%02X | %s | %s | %s%s |\n" % (r.id, r.name, ", ".join(r.verbs), note,
                                                " (service mode)" if r.service else ""))
        w("\n")
        for r in c.resources:
            w("### %s %s (0x%X/0x%02X)\n\n%s\n\n" % (c.title, r.name, c.id, r.id, r.doc))
            w("Verbs: %s" % ", ".join("`%s` = 0x%04X" % (v, ((S.VERB_VALUE[v] << 12) | (c.id << 8) | r.id))
                                      for v in r.verbs))
            if r.service:
                w(". **Needs service mode** (`SERVICE_MODE_REQUIRED` otherwise; reading is always allowed)")
            if r.sub == "interval":
                w(". SUBSCRIBE request: `u32 interval_ms` (50 .. 3600000); pushes `[issue_seq][page][response payload]`.")
            elif r.sub == "event":
                w(". SUBSCRIBE is event driven; request: %s." % (
                    ", ".join("`%s %s`" % (f.ctype, f.name) for f in r.sub_req) if r.sub_req else "`u32` (ignored)"))
            w("\n\n")
            if r.kind == "field":
                w("Value: `%s`%s, range %d .. %d. SET answers status only.\n\n"
                  % (r.ctype, (" in " + r.unit) if r.unit else "", r.lo, r.hi))
                continue
            if r.req_len is not None:
                w("Request payload: %d..%d bytes.\n\n" % r.req_len)
            if r.req:
                w("**Request** (%d bytes)\n\n%s\n\n" % (fields_size(r.req), md_fields(r.req)))
            elif r.req == [] and "EXECUTE" in r.verbs:
                w("Request payload: none.\n\n")
            if r.rsp:
                w("**Response** (%d bytes)\n\n%s\n\n" % (fields_size(r.rsp), md_fields(r.rsp)))
            if r.push:
                w("**Push payload** (after `[issue_seq][page]`)\n\n%s\n\n" % md_fields(r.push))
            if r.sub_req and r.sub == "event":
                w("**Subscribe request**\n\n%s\n\n" % md_fields(r.sub_req))
    return "".join(o)


OUTPUTS = {
    "Services/svc_api_defs.h": gen_defs_h,
    "Services/svc_api_tables.c": gen_tables_c,
    "PythonTestCode/apiv3_defs.py": gen_py,
    "docs/api-reference.md": gen_md,
    "tests/api_handler_stubs.inc": gen_stubs_inc,
}


def main():
    check_spec()
    check = "--check" in sys.argv
    bad = 0
    for rel, fn in OUTPUTS.items():
        text = fn()
        path = os.path.join(REPO, rel)
        old = None
        if os.path.exists(path):
            old = open(path, encoding="utf-8", newline="").read().replace("\r\n", "\n")
        if check:
            if old != text:
                print("OUT OF DATE:", rel)
                bad = 1
        else:
            if old != text:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
                print("wrote", rel)
    if check and not bad:
        print("generated API files are up to date")
    return bad


if __name__ == "__main__":
    sys.exit(main())
