# Writes ${OUT} (a header with FW_BUILD_ID) when its content changes: the commit the firmware was built from, "-dirty" if the
# working tree had uncommitted changes to tracked files, "nogit" when there is no repository (a source archive).
# Run at every build by the build_info target in CMakeLists.txt, so the id is never stale.
find_package(Git QUIET)
set(ID "nogit")
if(GIT_FOUND AND EXISTS "${SRC}/.git")
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" rev-parse --short=8 HEAD
                    OUTPUT_VARIABLE HASH OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE RC)
    if(RC EQUAL 0 AND HASH)
        set(ID "${HASH}")
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" status --porcelain --untracked-files=no
                        OUTPUT_VARIABLE STATUS OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(STATUS)
            set(ID "${ID}-dirty")
        endif()
    endif()
endif()
set(CONTENT "/* generated by cmake/build_info.cmake at build time -- do not edit or commit */\n#define FW_BUILD_ID \"${ID}\"\n")
set(OLD "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" OLD)
endif()
if(NOT OLD STREQUAL CONTENT)
    file(WRITE "${OUT}" "${CONTENT}")
endif()
